# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plus
version:      1.19
version_from: lib/CGI/Application/Plus.pm
installdirs:  site
requires:
    Class::constr:                 1.6
    Class::props:                  1.6
    Object::groups:                1.6
    Object::props:                 1.6

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
