# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plus
version:      1.21
version_from: lib/CGI/Application/Plus.pm
installdirs:  site
requires:
    Class::constr:                 2
    Class::props:                  2
    Object::groups:                2
    Object::props:                 2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
